### I- Création du fichier de production fictif pour tester le drift

In [9]:
import pandas as pd

# Dataset complet fourni
data = pd.read_csv("fichier_test.csv")

# Simulation :
train_data = data.sample(frac=0.7, random_state=42)  # données d'entraînement
prod_data = data.sample(frac=0.3, random_state=24)   # "fausse" production

# Sauvegarde des fichiers CSV
train_data.to_csv("train_data.csv", index=False)
prod_data.to_csv("prod_data.csv", index=False)

### II- Alignement pour créer des requettes une par une

In [1]:
import pandas as pd
prod = pd.read_csv("prod_data.csv")

**On ajouter les guillemets et les deux points pour préparer les colonnes pour fastapi**

In [2]:
prod.rename(columns=lambda x: f',"{x}":', inplace=True)

In [3]:
prod.rename(columns={',"EXT_SOURCE_2":' : '"EXT_SOURCE_2":'}, inplace=True )

In [4]:
T_prod = prod.T

In [5]:
T_prod = T_prod.fillna("NaN")

In [6]:
T_prod

,0,1,2,3,4,5,6,7,8,9,...,92243,92244,92245,92246,92247,92248,92249,92250,92251,92252
"""EXT_SOURCE_2"":",0.326031,0.31546,0.650611,0.634313,0.009017,0.526982,0.265312,0.05541,0.688154,0.547589,...,0.571213,0.293275,0.610186,0.704861,0.519154,0.479474,0.659441,0.492201,0.657956,0.348419
",""EXT_SOURCE_3"":",NaN,0.291097,0.490258,0.450747,NaN,0.535276,0.697147,0.621226,0.535276,0.432962,...,NaN,0.253963,0.583238,0.676993,0.297087,0.269286,0.092617,0.143758,0.647977,0.501075
",""NAME_EDUCATION_TYPE"":",1.0,3.0,1.0,1.0,1.0,1.0,1.0,3.0,3.0,1.0,...,1.0,1.0,1.0,1.0,1.0,1.0,3.0,3.0,1.0,1.0
",""CODE_GENDER_0_0"":",0.0,0.0,1.0,1.0,0.0,1.0,1.0,1.0,1.0,1.0,...,0.0,0.0,1.0,0.0,1.0,1.0,0.0,1.0,1.0,0.0
",""FLAG_DOCUMENT_3"":",1.0,0.0,1.0,1.0,1.0,0.0,0.0,1.0,1.0,1.0,...,1.0,1.0,1.0,1.0,0.0,0.0,1.0,1.0,0.0,1.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
",""COMMONAREA_AVG"":",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0105,0.006
",""WALLSMATERIAL_MODE_Stone_brick"":",1.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,1.0
",""DAYS_FIRST_DRAWING_max"":",365243.0,365243.0,365243.0,365243.0,365243.0,365243.0,365243.0,365243.0,365243.0,365243.0,...,365243.0,365243.0,365243.0,365243.0,365243.0,365243.0,365243.0,NaN,365243.0,365243.0
",""ORGANIZATION_TYPE_Trade_type_3"":",0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
",""AMT_DRAWINGS_CURRENT_mean"":",84982.5,NaN,NaN,NaN,NaN,NaN,NaN,10216.415455,0.0,28125.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,NaN

In [7]:
pd.set_option("display.max_rows", None)        # affiche toutes les lignes
#pd.set_option("display.max_columns", None)     # affiche toutes les colonnes
pd.set_option("display.width", None)           # empêche le retour à la ligne
pd.set_option("display.max_colwidth", None)    # affiche tout le contenu des cellules

**Visualisation**

In [8]:
T_prod

,0,1,2,3,4,5,6,7,8,9,...,92243,92244,92245,92246,92247,92248,92249,92250,92251,92252
"""EXT_SOURCE_2"":",0.326031,0.31546,0.650611,0.634313,0.009017,0.526982,0.265312,0.05541,0.688154,0.547589,...,0.571213,0.293275,0.610186,0.704861,0.519154,0.479474,0.659441,0.492201,0.657956,0.348419
",""EXT_SOURCE_3"":",NaN,0.291097,0.490258,0.450747,NaN,0.535276,0.697147,0.621226,0.535276,0.432962,...,NaN,0.253963,0.583238,0.676993,0.297087,0.269286,0.092617,0.143758,0.647977,0.501075
",""NAME_EDUCATION_TYPE"":",1.0,3.0,1.0,1.0,1.0,1.0,1.0,3.0,3.0,1.0,...,1.0,1.0,1.0,1.0,1.0,1.0,3.0,3.0,1.0,1.0
",""CODE_GENDER_0_0"":",0.0,0.0,1.0,1.0,0.0,1.0,1.0,1.0,1.0,1.0,...,0.0,0.0,1.0,0.0,1.0,1.0,0.0,1.0,1.0,0.0
",""FLAG_DOCUMENT_3"":",1.0,0.0,1.0,1.0,1.0,0.0,0.0,1.0,1.0,1.0,...,1.0,1.0,1.0,1.0,0.0,0.0,1.0,1.0,0.0,1.0
",""NAME_CONTRACT_STATUS_most_use_Refused"":",0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,1.0,1.0,0.0,0.0,0.0,0.0
",""NAME_INCOME_TYPE"":",0.0,0.0,0.0,3.0,0.0,1.0,2.0,1.0,0.0,0.0,...,0.0,0.0,2.0,2.0,2.0,0.0,0.0,0.0,2.0,0.0
",""CNT_DRAWINGS_ATM_CURRENT_mean"":",5.0,NaN,NaN,NaN,NaN,NaN,NaN,0.0,NaN,0.25,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
",""EXT_SOURCE_1"":",NaN,NaN,0.50368,0.399786,0.182224,NaN,NaN,0.246244,NaN,NaN,...,0.247182,0.1207,NaN,NaN,NaN,0.270297,NaN,0.354767,NaN,0.150539
",""FLAG_OWN_CAR_0_0"":",1.0,0.0,1.0,0.0,1.0,1.0,1.0,1.0,0.0,1.0,...,0.0,1.0,0.0,0.0,0.0,1.0,1.0,1.0,1.0,1.0
",""PAYMENT_RATIO_mean"":",1.0,1.0,1.0,1.0,1.0,0.8,1.0,1.0,1.0,0.923077,...,1.0,0.75,1.154381,1.406513,0.918919,1.0,0.916667,NaN,0.981651,0.897959
",""MONTHS_BALANCE_std"":",2.160247,2.44949,2.160247,2.44949,4.639376,6.645084,24.355013,3.316625,18.118089,11.071957,...,17.079689,2.160247,4.1833,11.937336,19.350557,1.870829,7.96687,NaN,18.339258,23.109544
",""CNT_PAYMENT_max"":",6.0,6.0,12.0,36.0,12.0,24.0,12.0,10.0,12.0,36.0,...,24.0,6.0,12.0,24.0,48.0,12.0,12.0,NaN,36.0,24.0
",""BALANCE_LIMIT_RATIO_max"":",1.046728,NaN,NaN,NaN,NaN,NaN,NaN,0.548532,0.0,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,NaN
",""DAYS_BIRTH"":",-12198.0,-14859.0,-13171.0,-19631.0,-8047.0,-17627.0,-22411.0,-14196.0,-15357.0,-16350.0,...,-13580.0,-8843.0,-20864.0,-19470.0,-23300.0,-11905.0,-10707.0,-10107.0,-21812.0,-10764.0
",""SK_ID_PREV_nunique"":",1.0,1.0,1.0,1.0,3.0,2.0,2.0,2.0,2.0,5.0,...,6.0,1.0,1.0,2.0,2.0,1.0,2.0,NaN,8.0,4.0
",""NAME_FAMILY_STATUS_Married"":",0.0,1.0,1.0,1.0,0.0,1.0,1.0,1.0,0.0,1.0,...,0.0,1.0,0.0,1.0,0.0,1.0,1.0,1.0,1.0,1.0
",""CNT_DRAWINGS_CURRENT_mean"":",7.0,NaN,NaN,NaN,NaN,NaN,NaN,2.909091,0.0,0.25,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,NaN
",""AMT_DOWN_PAYMENT_max"":",13500.0,0.0,0.0,3784.5,0.0,20313.0,18000.0,0.0,1800.0,0.0,...,32211.0,2250.0,0.0,0.0,7029.0,3420.0,17100.0,NaN,9225.0,17280.0
",""FLAG_DOCUMENT_6"":",0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0
",""NAME_YIELD_GROUP_most_use"":",4.0,3.0,2.0,4.0,2.0,0.0,3.0,4.0,4.0,4.0,...,2.0,3.0,2.0,0.0,1.0,3.0,4.0,5.0,2.0,3.0
",""REGION_RATING_CLIENT"":",2.0,2.0,3.0,2.0,3.0,2.0,2.0,2.0,2.0,2.0,...,2.0,2.0,3.0,2.0,2.0,2.0,1.0,2.0,2.0,3.0
",""DEF_30_CNT_SOCIAL_CIRCLE"":",0.0,0.0,0.0,0.0,0.0,1.0,1.0,0.0,0.0,0.0,...,1.0,0.0,0.0,0.0,0.0,2.0,0.0,1.0,0.0,0.0
",""WALLSMATERIAL_MODE_Panel"":",0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
",""DAYS_LATE_max"":",0.0,-3.0,-8.0,0.0,-2.0,12.0,-7.0,2.0,-5.0,11.0,...,1.0,3.0,-10.0,-9.0,209.0,-9.0,5.0,NaN,3.0,30.0
",""REG_CITY_NOT_LIVE_CITY"":",0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,1.0
",""DAYS_EMPLOYED"":",-127.0,-6973.0,-3652.0,-3259.0,-262.0,-1928.0,365243.0,-831.0,-489.0,-4554.0,...,-2714.0,-495.0,365243.0,365243.0,365243.0,-2470.0,-1506.0,-539.0,365243.0,-1532.0
",""SK_DPD_DEF_max"":",0.0,0.0,0.0,0.0,0.0,11.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,1.0,0.0,0.0,NaN,0.0,3.0
",""NAME_CONTRACT_TYPE_most_use_Cash_loans"":",0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0,...,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0,1.0
",""AMT_INSTALMENT_sum"":",256157.46,148771.305,66402.63,43694.37,88267.32,402028.74,249823.395,179018.685,59687.505,1215799.695,...,652016.025,28662.48,139836.735,80622.09,428528.61,42767.01,207402.03,NaN,1717341.3,878132.25
",""CODE_REJECT_REASON_most_use_HC"":",0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0
",""NAME_GOODS_CATEGORY_most_use_Clothing_and_Accessories"":",0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
",""OCCUPATION_TYPE_Core_staff"":",0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0
",""ORGANIZATION_TYPE_Transport_type_3"":",0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
",""AMT_CREDIT"":",474048.0,152820.0,704844.0,1042164.0,296505.0,270000.0,49500.0,521280.0,803259.0,450000.0,...,540000.0,228915.0,517500.0,904500.0,161730.0,720000.0,485640.0,325908.0,203760.0,288873.0
",""OWN_CAR_AGE"":",NaN,10.0,NaN,17.0,NaN,NaN,NaN,NaN,11.0,NaN,...,9.0,NaN,16.0,25.0,1.0,NaN,NaN,NaN,NaN,NaN
",""CODE_REJECT_REASON_most_use_SCOFR"":",0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
",""NAME_CONTRACT_TYPE_Cash_loans"":",1.0,1.0,1.0,1.0,1.0,0.0,1.0,1.0,1.0,1.0,...,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0
",""CNT_INSTALMENT_FUTURE_max"":",5.0,6.0,12.0,6.0,12.0,12.0,12.0,10.0,12.0,14.0,...,24.0,6.0,12.0,24.0,24.0,5.0,12.0,NaN,36.0,24.0
",""NAME_GOODS_CATEGORY_most_use_Furniture"":",0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
",""DRAWINGS_LIMIT_RATIO_mean"":",0.94425,NaN,NaN,NaN,NaN,NaN,NaN,0.102831,0.0,2812500000.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,NaN
",""AMT_ANNUITY"":",24817.5,16047.0,32791.5,44284.5,27324.0,13500.0,4950.0,19449.0,26041.5,47254.5,...,19525.5,16785.0,18715.5,35869.5,7254.0,39060.0,39069.0,12541.5,10782.0,19435.5
",""DAYS_LAST_DUE_1ST_VERSION_max"":",365243.0,-951.0,134.0,-1586.0,259.0,-1849.0,-83.0,365243.0,365243.0,365243.0,...,-998.0,-574.0,-251.0,593.0,-77.0,-1347.0,-634.0,NaN,365243.0,277.0
",""DAYS_DECISION_min"":",-1285.0,-1132.0,-226.0,-1775.0,-415.0,-2559.0,-1859.0,-318.0,-1264.0,-984.0,...,-2885.0,-755.0,-612.0,-825.0,-1818.0,-1708.0,-1402.0,NaN,-2272.0,-2507.0
",""AMT_DIFF_mean"":",0.0,0.0,0.0,0.0,0.0,3529.26,0.0,0.0,0.0,3294.0,...,0.0,895.7025,-1728.526154,-2500.0,937.300135,0.0,714.21,NaN,214.128991,1778.710408
",""AMT_DRAWINGS_ATM_CURRENT_mean"":",82350.0,NaN,NaN,NaN,NaN,NaN,NaN,0.0,NaN,28125.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
",""NUM_INSTALMENT_NUMBER_max"":",5.0,6.0,7.0,6.0,6.0,12.0,12.0,19.0,6.0,6.0,...,24.0,6.0,12.0,4.0,24.0,5.0,12.0,NaN,18.0,23.0
",""FLOORSMAX_AVG"":",0.0833,0.375,NaN,NaN,NaN,NaN,0.0417,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.1667,0.0833
",""NAME_TYPE_SUITE_most_use_Other_A"":",0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
",""PRODUCT_COMBINATION_most_use_Card_Street"":",1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,1.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
",""ORGANIZATION_TYPE_Self_employed"":",0.0,0.0,0.0,0.0,1.0,1.0,0.0,1.0,0.0,0.0,...,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
",""AMT_REQ_CREDIT_BUREAU_QRT"":",NaN,0.0,0.0,0.0,NaN,0.0,0.0,0.0,0.0,0.0,...,0.0,4.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0
",""SK_DPD_min"":",0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,NaN,0.0,0.0
",""MONTHS_BALANCE_max"":",-37.0,-31.0,-2.0,-52.0,-1.0,-62.0,-2.0,-1.0,-2.0,-2.0,...,-33.0,-19.0,-8.0,-1.0,-2.0,-51.0,-21.0,NaN,-2.0,-5.0
",""EMERGENCYSTATE_MODE_0_0"":",1.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,1.0
",""AMT_BALANCE_max"":",94205.565,NaN,NaN,NaN,NaN,NaN,NaN,75076.065,0.0,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,NaN
",""DAYS_ID_PUBLISH"":",-2682.0,-4257.0,-4536.0,-3121.0,-694.0,-1136.0,-5112.0,-478.0,-4029.0,-3373.0,...,-4402.0,-1520.0,-3889.0,-2092.0,-4074.0,-2028.0,-1610.0,-1789.0,-4639.0,-3377.0
",""DAYS_FIRST_DUE_min"":",-1253.0,-1101.0,-196.0,-1736.0,-385.0,-2490.0,-1811.0,-287.0,-1233.0,-872.0,...,-2846.0,-724.0,-581.0,-794.0,-1787.0,-1677.0,-1371.0,NaN,-2238.0,-2473.0
",""ORGANIZATION_TYPE_Postal"":",0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
",""FLAG_DOCUMENT_18"":",0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
",""DAYS_LAST_DUE_mean"":",182055.0,-951.0,365243.0,-1586.0,273873.5,-2064.5,-782.0,182613.0,243134.333333,72686.6,...,-1556.333333,-574.0,-251.0,182269.5,-797.0,-1557.0,-867.5,NaN,121034.555556,-791.75
",""DAYS_DECISION_mean"":",-335.75,-1132.0,-226.0,-485.4,-157.2,-2128.4,-1122.0,-318.0,-538.666667,-376.0,...,-1969.285714,-755.0,-612.0,-477.5,-455.222222,-1708.0,-1019.0,NaN,-868.083333,-899.5
",""NAME_SELLER_INDUSTRY_most_use_Industry"":",0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
",""OCCUPATION_TYPE_Laborers"":",0.0,0.0,0.0,0.0,1.0,1.0,0.0,0.0,0.0,0.0,...,1.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
",""NAME_CLIENT_TYPE_most_use_Repeater"":",0.0,0.0,0.0,0.0,1.0,1.0,0.0,0.0,0.0,1.0,...,1.0,0.0,0.0,0.0,1.0,0.0,1.0,0.0,1.0,1.0
",""NAME_CLIENT_TYPE_most_use_Refreshed"":",1.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,1.0,0.0,...,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0
",""ORGANIZATION_TYPE_Industry_type_3"":",0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
",""NAME_TYPE_SUITE_Unaccompanied"":",1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,...,1.0,1.0,1.0,0.0,0.0,1.0,1.0,0.0,1.0,1.0
",""ORGANIZATION_TYPE_Construction"":",0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
",""ORGANIZATION_TYPE_Other"":",1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
",""CHANNEL_TYPE_most_use_AP_Cash_loan"":",0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
",""CHANNEL_TYPE_most_use_Channel_of_corporate_sales"":",0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
",""PRODUCT_COMBINATION_most_use_POS_mobile_with_interest"":",0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0
",""OCCUPATION_TYPE_Drivers"":",0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
",""AMT_ANNUITY_min"":",4500.0,24809.265,9486.09,7280.775,5956.74,5807.835,5821.11,2250.0,2250.0,0.0,...,2091.78,3582.81,11703.24,5134.545,2255.85,4049.325,8570.52,NaN,4500.0,6804.0
",""RATE_DOWN_PAYMENT_max"":",0.059787,0.0,0.0,0.104367,0.0,0.115472,0.217818,0.0,0.104519,0.0,...,0.421048,0.123648,0.0,0.0,0.089738,0.100146,0.21783,NaN,0.101382,0.167304
",""HOUSETYPE_MODE_specific_housing"":",0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
",""AMT_REQ_CREDIT_BUREAU_MON"":",NaN,0.0,0.0,1.0,NaN,0.0,0.0,0.0,0.0,0.0,...,0.0,1.0,0.0,8.0,0.0,1.0,0.0,0.0,0.0,0.0
",""LIVE_REGION_NOT_WORK_REGION"":",0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
",""SK_DPD_max"":",0.0,0.0,0.0,0.0,0.0,11.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,185.0,0.0,0.0,NaN,0.0,29.0
",""AMT_REQ_CREDIT_BUREAU_WEEK"":",NaN,0.0,0.0,0.0,NaN,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
",""AMT_CREDIT_LIMIT_ACTUAL_max"":",90000.0,NaN,NaN,NaN,NaN,NaN,NaN,225000.0,180000.0,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,90000.0,NaN
",""ORGANIZATION_TYPE_Industry_type_9"":",0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
",""FLAG_DOCUMENT_16"":",0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
",""NAME_FAMILY_STATUS_Single_not_married"":",1.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
",""CHANNEL_TYPE_most_use_Country_wide"":",0.0,0.0,0.0,0.0,0.0,1.0,1.0,1.0,0.0,0.0,...,0.0,1.0,0.0,1.0,1.0,1.0,1.0,0.0,0.0,0.0
",""CNT_INSTALMENT_FUTURE_min"":",0.0,0.0,6.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,NaN,0.0,0.0
",""OCCUPATION_TYPE_Low_skill_Laborers"":",1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
",""FLAG_WORK_PHONE"":",0.0,1.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,...,0.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0
",""DAYS_LAST_DUE_max"":",365243.0,-951.0,365243.0,-1586.0,365243.0,-1849.0,-83.0,365243.0,365243.0,365243.0,...,-998.0,-574.0,-251.0,365243.0,-77.0,-1557.0,-634.0,NaN,365243.0,-173.0
",""DAYS_LAST_PHONE_CHANGE"":",-19.0,-1132.0,-226.0,-1775.0,-415.0,0.0,-1859.0,-625.0,0.0,-984.0,...,-1572.0,-38.0,0.0,-3340.0,-217.0,-1708.0,-1402.0,-16.0,-1907.0,-863.0
",""ORGANIZATION_TYPE_Government"":",0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
",""NAME_TYPE_SUITE_Other_B"":",0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
",""ORGANIZATION_TYPE_Military"":",0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
",""PRODUCT_COMBINATION_most_use_Cash_Street_low"":",0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
",""YEARS_BEGINEXPLUATATION_AVG"":",0.9627,NaN,NaN,NaN,NaN,NaN,0.9687,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.9861,0.9727
",""CNT_PAYMENT_min"":",0.0,6.0,12.0,6.0,4.0,10.0,10.0,0.0,0.0,0.0,...,7.0,6.0,12.0,12.0,10.0,6.0,10.0,NaN,0.0,0.0
",""SELLERPLACE_AREA_max"":",980.0,247.0,148.0,88.0,123.0,1000.0,40.0,2194.0,40.0,6900.0,...,240.0,100.0,2209.0,2326.0,467.0,40.0,1900.0,NaN,70.0,3000.0
",""AMT_DIFF_max"":",0.0,0.0,0.0,0.0,0.0,20411.1,0.0,0.0,0.0,42752.61,...,0.0,3572.55,0.0,0.0,11892.24,0.0,8564.58,NaN,10976.4,18047.16
",""NAME_SELLER_INDUSTRY_most_use_Construction"":",0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
",""DAYS_FIRST_DRAWING_mean"":",182612.0,365243.0,365243.0,365243.0,365243.0,365243.0,365243.0,182465.0,365243.0,292142.2,...,365243.0,365243.0,365243.0,365243.0,365243.0,365243.0,365243.0,NaN,365243.0,365243.0
",""HOUR_APPR_PROCESS_START_max"":",18.0,14.0,12.0,16.0,11.0,18.0,14.0,15.0,18.0,18.0,...,16.0,14.0,14.0,19.0,12.0,15.0,20.0,NaN,17.0,14.0
",""LIVE_CITY_NOT_WORK_CITY"":",1.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,...,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
",""NAME_HOUSING_TYPE_Rented_apartment"":",0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
",""PRODUCT_COMBINATION_most_use_Cash_Street_high"":",0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
",""ORGANIZATION_TYPE_Business_Entity_Type_3"":",0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,1.0,1.0,0.0,0.0,1.0
",""NAME_CONTRACT_TYPE_most_use_Revolving_loans"":",1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
",""ORGANIZATION_TYPE_School"":",0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
",""ORGANIZATION_TYPE_Kindergarten"":",0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0
",""DAYS_LAST_DUE_min"":",-1133.0,-951.0,365243.0,-1586.0,-235.0,-2280.0,-1481.0,-17.0,-1083.0,-812.0,...,-2576.0,-574.0,-251.0,-704.0,-1517.0,-1557.0,-1101.0,NaN,-1968.0,-2323.0
",""CNT_DRAWINGS_CURRENT_sum"":",7.0,NaN,NaN,NaN,NaN,NaN,NaN,32.0,0.0,2.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,NaN
",""OCCUPATION_TYPE_Accountants"":",0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
",""BASEMENTAREA_AVG"":",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0718,0.0
",""NAME_HOUSING_TYPE_Municipal_apartment"":",0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
",""OCCUPATION_TYPE_Security_staff"":",0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
",""CHANNEL_TYPE_most_use_Contact_center"":",0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
",""AMT_INSTALMENT_mean"":",51231.492,24795.2175,9486.09,7282.395,6789.793846,16081.1496,11355.608864,6173.058103,5426.136818,93523.053462,...,9183.324296,3582.81,10756.671923,8958.01,11581.854324,8553.402,8641.75125,NaN,15755.424771,17921.066327
",""ORGANIZATION_TYPE_Trade_type_2"":",0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
",""AMT_PAYMENT_CURRENT_max"":",0.0,NaN,NaN,NaN,NaN,NaN,NaN,44356.545,NaN,225000.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
",""EMERGENCYSTATE_MODE_1_0"":",0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
",""ORGANIZATION_TYPE_Transport_type_2"":",0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
",""AMT_REQ_CREDIT_BUREAU_YEAR"":",NaN,1.0,0.0,2.0,NaN,0.0,0.0,2.0,1.0,3.0,...,1.0,2.0,1.0,0.0,4.0,1.0,1.0,0.0,5.0,2.0
",""PRODUCT_COMBINATION_most_use_POS_industry_with_interest"":",0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
",""FLAG_DOCUMENT_11"":",0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
",""AMT_REQ_CREDIT_BUREAU_DAY"":",NaN,0.0,0.0,0.0,NaN,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
",""AMT_DIFF_min"":",0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,-11703.24,-17340.75,0.0,0.0,0.0,NaN,0.0,0.0
",""AMT_DRAWINGS_POS_CURRENT_mean"":",2632.5,NaN,NaN,NaN,NaN,NaN,NaN,11238.057,NaN,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
",""SK_ID_PREV_count"":",4.0,1.0,1.0,5.0,5.0,5.0,2.0,2.0,3.0,10.0,...,7.0,1.0,1.0,2.0,9.0,4.0,3.0,NaN,12.0,8.0
",""NAME_CONTRACT_STATUS_most_use_Active"":",1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,...,1.0,1.0,1.0,1.0,1.0,1.0,1.0,0.0,1.0,1.0
",""AMT_DRAWINGS_ATM_CURRENT_sum"":",82350.0,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,225000.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,NaN
",""ENTRANCES_AVG"":",0.069,0.1379,NaN,NaN,NaN,NaN,0.0345,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.1379,0.1379
",""DAYS_REGISTRATION"":",-6319.0,-3488.0,-5336.0,-11914.0,-8047.0,-8416.0,-399.0,-3915.0,-1614.0,-2855.0,...,-200.0,-106.0,-8017.0,-1249.0,-6345.0,-279.0,-1214.0,-10103.0,-10132.0,-4381.0
",""NAME_PRODUCT_TYPE_most_use_x_sell"":",0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0,1.0
",""NAME_FAMILY_STATUS_Civil_marriage"":",0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0
",""ORGANIZATION_TYPE_Security_Ministries"":",0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
",""DAYS_LATE_mean"":",-20.6,-9.166667,-11.285714,-14.166667,-18.615385,-8.08,-19.363636,-7.0,-12.454545,-11.846154,...,-10.323944,-8.25,-21.692308,-39.333333,1.351351,-17.4,-18.125,NaN,-8.137615,-19.061224
",""ORGANIZATION_TYPE_Bank"":",0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
",""ORGANIZATION_TYPE_Business_Entity_Type_2"":",0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
",""SELLERPLACE_AREA_mean"":",244.25,247.0,148.0,16.8,46.4,600.6,35.0,2194.0,33.333333,1441.5,...,97.571429,100.0,2209.0,2326.0,96.666667,36.75,1550.333333,NaN,4.916667,548.875
",""NONLIVINGAREA_AVG"":",0.0145,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0505,0.0225
",""CNT_DRAWINGS_ATM_CURRENT_sum"":",5.0,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,2.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,NaN
",""NAME_HOUSING_TYPE_House_apartment"":",1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,0.0,...,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0
",""PRODUCT_COMBINATION_most_use_Cash_X_Sell_middle"":",0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
",""AMT_INCOME_TOTAL"":",157500.0,112500.0,90000.0,126000.0,130500.0,121500.0,67500.0,112500.0,225000.0,112500.0,...,135000.0,112500.0,247500.0,180000.0,49500.0,135000.0,211500.0,67500.0,252000.0,166500.0
",""NAME_FAMILY_STATUS_Separated"":",0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,...,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
",""ORGANIZATION_TYPE_Legal_Services"":",0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [9]:
T_prod.to_csv("prod_data_transposée.csv", header=False)

Après cette exportation, on pourra donc ouvrir le fichier sur Excel et sélection toutes les colonnes de features avec les informations de quelques clients sur ce fichier pour tester sur fastapi et créer des requettes

*Exemple d'aligement ci-dessous pour le client 0: on sélectionne toutes les features avec la colonne 0, et on ajoute les crochets au debut et à la fin, et ajouter la virgule à la fin de chaque valeur, il nous reste donc juste à coller dans Fastapi*

**NB : Manipulation à faire plus facilement sur Excel**

In [ ]:
{ 
 "EXT_SOURCE_2":	0.326030701
,"EXT_SOURCE_3":	NaN
,"NAME_EDUCATION_TYPE":	1
,"CODE_GENDER_0_0":	0
,"FLAG_DOCUMENT_3":	1
,"NAME_CONTRACT_STATUS_most_use_Refused":	0
,"NAME_INCOME_TYPE":	0
,"CNT_DRAWINGS_ATM_CURRENT_mean":	5
,"EXT_SOURCE_1":	NaN
,"FLAG_OWN_CAR_0_0":	1
,"PAYMENT_RATIO_mean":	1
,"MONTHS_BALANCE_std":	2.160246899
,"CNT_PAYMENT_max":	6
,"BALANCE_LIMIT_RATIO_max":	1.0467285
,"DAYS_BIRTH":	-12198
,"SK_ID_PREV_nunique":	1
,"NAME_FAMILY_STATUS_Married":	0
,"CNT_DRAWINGS_CURRENT_mean":	7
,"AMT_DOWN_PAYMENT_max":	13500
,"FLAG_DOCUMENT_6":	0
,"NAME_YIELD_GROUP_most_use":	4
,"REGION_RATING_CLIENT":	2
,"DEF_30_CNT_SOCIAL_CIRCLE":	0
,"WALLSMATERIAL_MODE_Panel":	0
,"DAYS_LATE_max":	0
,"REG_CITY_NOT_LIVE_CITY":	0
,"DAYS_EMPLOYED":	-127
,"SK_DPD_DEF_max":	0
,"NAME_CONTRACT_TYPE_most_use_Cash_loans":	0
,"AMT_INSTALMENT_sum":	256157.46
,"CODE_REJECT_REASON_most_use_HC":	0
,"NAME_GOODS_CATEGORY_most_use_Clothing_and_Accessories":	0
,"OCCUPATION_TYPE_Core_staff":	0
,"ORGANIZATION_TYPE_Transport_type_3":	0
,"AMT_CREDIT":	474048
,"OWN_CAR_AGE":	NaN
,"CODE_REJECT_REASON_most_use_SCOFR":	0
,"NAME_CONTRACT_TYPE_Cash_loans":	1
,"CNT_INSTALMENT_FUTURE_max":	5
,"NAME_GOODS_CATEGORY_most_use_Furniture":	0
,"DRAWINGS_LIMIT_RATIO_mean":	0.94425
,"AMT_ANNUITY":	24817.5
,"DAYS_LAST_DUE_1ST_VERSION_max":	365243
,"DAYS_DECISION_min":	-1285
,"AMT_DIFF_mean":	0
,"AMT_DRAWINGS_ATM_CURRENT_mean":	82350
,"NUM_INSTALMENT_NUMBER_max":	5
,"FLOORSMAX_AVG":	0.0833
,"NAME_TYPE_SUITE_most_use_Other_A":	0
,"PRODUCT_COMBINATION_most_use_Card_Street":	1
,"ORGANIZATION_TYPE_Self_employed":	0
,"AMT_REQ_CREDIT_BUREAU_QRT":	NaN
,"SK_DPD_min":	0
,"MONTHS_BALANCE_max":	-37
,"EMERGENCYSTATE_MODE_0_0":	1
,"AMT_BALANCE_max":	94205.565
,"DAYS_ID_PUBLISH":	-2682
,"DAYS_FIRST_DUE_min":	-1253
,"ORGANIZATION_TYPE_Postal":	0
,"FLAG_DOCUMENT_18":	0
,"DAYS_LAST_DUE_mean":	182055
,"DAYS_DECISION_mean":	-335.75
,"NAME_SELLER_INDUSTRY_most_use_Industry":	0
,"OCCUPATION_TYPE_Laborers":	0
,"NAME_CLIENT_TYPE_most_use_Repeater":	0
,"NAME_CLIENT_TYPE_most_use_Refreshed":	1
,"ORGANIZATION_TYPE_Industry_type_3":	0
,"NAME_TYPE_SUITE_Unaccompanied":	1
,"ORGANIZATION_TYPE_Construction":	0
,"ORGANIZATION_TYPE_Other":	1
,"CHANNEL_TYPE_most_use_AP_Cash_loan":	0
,"CHANNEL_TYPE_most_use_Channel_of_corporate_sales":	0
,"PRODUCT_COMBINATION_most_use_POS_mobile_with_interest":	0
,"OCCUPATION_TYPE_Drivers":	0
,"AMT_ANNUITY_min":	4500
,"RATE_DOWN_PAYMENT_max":	0.059786505
,"HOUSETYPE_MODE_specific_housing":	0
,"AMT_REQ_CREDIT_BUREAU_MON":	NaN
,"LIVE_REGION_NOT_WORK_REGION":	0
,"SK_DPD_max":	0
,"AMT_REQ_CREDIT_BUREAU_WEEK":	NaN
,"AMT_CREDIT_LIMIT_ACTUAL_max":	90000
,"ORGANIZATION_TYPE_Industry_type_9":	0
,"FLAG_DOCUMENT_16":	0
,"NAME_FAMILY_STATUS_Single_not_married":	1
,"CHANNEL_TYPE_most_use_Country_wide":	0
,"CNT_INSTALMENT_FUTURE_min":	0
,"OCCUPATION_TYPE_Low_skill_Laborers":	1
,"FLAG_WORK_PHONE":	0
,"DAYS_LAST_DUE_max":	365243
,"DAYS_LAST_PHONE_CHANGE":	-19
,"ORGANIZATION_TYPE_Government":	0
,"NAME_TYPE_SUITE_Other_B":	0
,"ORGANIZATION_TYPE_Military":	0
,"PRODUCT_COMBINATION_most_use_Cash_Street_low":	0
,"YEARS_BEGINEXPLUATATION_AVG":	0.9627
,"CNT_PAYMENT_min":	0
,"SELLERPLACE_AREA_max":	980
,"AMT_DIFF_max":	0
,"NAME_SELLER_INDUSTRY_most_use_Construction":	0
,"DAYS_FIRST_DRAWING_mean":	182612
,"HOUR_APPR_PROCESS_START_max":	18
,"LIVE_CITY_NOT_WORK_CITY":	1
,"NAME_HOUSING_TYPE_Rented_apartment":	0
,"PRODUCT_COMBINATION_most_use_Cash_Street_high":	0
,"ORGANIZATION_TYPE_Business_Entity_Type_3":	0
,"NAME_CONTRACT_TYPE_most_use_Revolving_loans":	1
,"ORGANIZATION_TYPE_School":	0
,"ORGANIZATION_TYPE_Kindergarten":	0
,"DAYS_LAST_DUE_min":	-1133
,"CNT_DRAWINGS_CURRENT_sum":	7
,"OCCUPATION_TYPE_Accountants":	0
,"BASEMENTAREA_AVG":	NaN
,"NAME_HOUSING_TYPE_Municipal_apartment":	0
,"OCCUPATION_TYPE_Security_staff":	0
,"CHANNEL_TYPE_most_use_Contact_center":	0
,"AMT_INSTALMENT_mean":	51231.492
,"ORGANIZATION_TYPE_Trade_type_2":	0
,"AMT_PAYMENT_CURRENT_max":	0
,"EMERGENCYSTATE_MODE_1_0":	0
,"ORGANIZATION_TYPE_Transport_type_2":	0
,"AMT_REQ_CREDIT_BUREAU_YEAR":	NaN
,"PRODUCT_COMBINATION_most_use_POS_industry_with_interest":	0
,"FLAG_DOCUMENT_11":	0
,"AMT_REQ_CREDIT_BUREAU_DAY":	NaN
,"AMT_DIFF_min":	0
,"AMT_DRAWINGS_POS_CURRENT_mean":	2632.5
,"SK_ID_PREV_count":	4
,"NAME_CONTRACT_STATUS_most_use_Active":	1
,"AMT_DRAWINGS_ATM_CURRENT_sum":	82350
,"ENTRANCES_AVG":	0.069
,"DAYS_REGISTRATION":	-6319
,"NAME_PRODUCT_TYPE_most_use_x_sell":	0
,"NAME_FAMILY_STATUS_Civil_marriage":	0
,"ORGANIZATION_TYPE_Security_Ministries":	0
,"DAYS_LATE_mean":	-20.6
,"ORGANIZATION_TYPE_Bank":	0
,"ORGANIZATION_TYPE_Business_Entity_Type_2":	0
,"SELLERPLACE_AREA_mean":	244.25
,"NONLIVINGAREA_AVG":	0.0145
,"CNT_DRAWINGS_ATM_CURRENT_sum":	5
,"NAME_HOUSING_TYPE_House_apartment":	1
,"PRODUCT_COMBINATION_most_use_Cash_X_Sell_middle":	0
,"AMT_INCOME_TOTAL":	157500
,"NAME_FAMILY_STATUS_Separated":	0
,"ORGANIZATION_TYPE_Legal_Services":	0
,"ORGANIZATION_TYPE_Realtor":	0
,"REGION_POPULATION_RELATIVE":	0.006233
,"NAME_TYPE_SUITE_Spouse_partner":	0
,"ORGANIZATION_TYPE_Industry_type_11":	0
,"ORGANIZATION_TYPE_Trade_type_6":	0
,"ORGANIZATION_TYPE_Trade_type_7":	0
,"ORGANIZATION_TYPE_Restaurant":	0
,"WALLSMATERIAL_MODE_Block":	0
,"AMT_GOODS_PRICE_min":	90000
,"PRODUCT_COMBINATION_most_use_Card_X_Sell":	0
,"DAYS_DECISION_max":	-19
,"FLAG_DOCUMENT_13":	0
,"FLOORSMIN_AVG":	0.125
,"ORGANIZATION_TYPE_Industry_type_12":	0
,"NAME_HOUSING_TYPE_With_parents":	0
,"PRODUCT_COMBINATION_most_use_POS_industry_without_interest":	0
,"AMT_DRAWINGS_CURRENT_sum":	84982.5
,"AMT_ANNUITY_max":	42919.11
,"NONLIVINGAPARTMENTS_AVG":	NaN
,"NAME_CONTRACT_STATUS_most_use_Signed":	0
,"APARTMENTS_AVG":	0.0247
,"HOUR_APPR_PROCESS_START_std":	1.732050808
,"AMT_APPLICATION_mean":	81554.625
,"CNT_CHILDREN":	0
,"NAME_CASH_LOAN_PURPOSE_most_use_Buying_a_holiday_home_land":	0
,"DAYS_LATE_min":	-46
,"OCCUPATION_TYPE_High_skill_tech_staff":	0
,"OCCUPATION_TYPE_Cleaning_staff":	0
,"OBS_30_CNT_SOCIAL_CIRCLE":	7
,"NAME_PORTFOLIO_most_use_Cash":	0
,"NAME_HOUSING_TYPE_Office_apartment":	0
,"NAME_SELLER_INDUSTRY_most_use_Auto_technology":	0
,"HOUR_APPR_PROCESS_START":	12
,"CHANNEL_TYPE_most_use_Stone":	0
,"NAME_TYPE_SUITE_most_use_Unaccompanied":	1
,"CHANNEL_TYPE_most_use_Credit_and_cash_offices":	1
,"COMMONAREA_AVG":	NaN
,"WALLSMATERIAL_MODE_Stone_brick":	1
,"DAYS_FIRST_DRAWING_max":	365243
,"ORGANIZATION_TYPE_Trade_type_3":	0
,"AMT_DRAWINGS_CURRENT_mean":	84982.5
}